CREATE TABLE composicion_alimentos (
    id SERIAL PRIMARY KEY,
    codigo TEXT,
    nombre TEXT,
    grupo TEXT,
    energia_kcal INTEGER,
    energia_kj INTEGER,
    agua_g NUMERIC,
    prote_total_g NUMERIC,
    prote_veg_g NUMERIC,
    prote_anim_g NUMERIC,
    grasa_total_g NUMERIC,
    carbo_total_g NUMERIC,
    carbo_dispo_g NUMERIC,
    fibra_dietaria_g NUMERIC,
    cenizas_g NUMERIC,
    calcio_mg NUMERIC,
    fosforo_mg NUMERIC,
    zinc_mg NUMERIC,
    hierro_mg NUMERIC,
    caroteno_tot_ug NUMERIC,
    vitamina_a_tot_ug NUMERIC,
    tiamina_mg TEXT,
    riboflavina_mg NUMERIC,
    niacina_mg NUMERIC,
    vitamina_c_mg NUMERIC,
    acido_folico_ug NUMERIC,
    sodio_mg NUMERIC,
    potasio_mg NUMERIC
);
